PriceStatistics/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('r/',include('receipt.urls'))

]

main/urls.py
from main.views import *
from django.urls import path

urlpatterns = [
    path('', main_view),
    path('sales', sales_view),
    path('category/<slug:slug>', page_view, name='category_detail'),
    path('category/<str:name>/<slug:slug>', item_view, name='item-detail'),
]

receipt/urls.py

from receipt.views import *
from django.urls import path

urlpatterns = [
    path('', receipt),
]

main/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
# Create your models here.
from django.db import models


class RootCategory(models.Model):
    DEFAULT_PK = 1
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'


class Category(models.Model):
    DEFAULT_PK = 1
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    root_category = models.ForeignKey(RootCategory,on_delete=models.CASCADE,verbose_name='Родительская категория',default=RootCategory.DEFAULT_PK)

    def __str__(self):
        return self.name

    @property
    def get_products(self):
        return Item.objects.filter(category__name=self.name)

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name_plural = 'Подкатегории'
        verbose_name = 'Подкатегория'


# Create your models here.
class Item(models.Model):

    name = models.TextField(max_length=512,db_index=True)
    biggest = models.TextField(default='no-image.png')
    large = models.TextField(default='no-image.png')
    medium = models.TextField(default='no-image.png')
    small = models.TextField(default='no-image.png')
    weight = models.IntegerField(default=0)
    display_weight = models.CharField(default='-',max_length=15)
    popular = models.BooleanField(default=False)
    slug = models.SlugField(default='slug',unique=True,max_length=256)
    description = models.TextField()
    composition = models.TextField(default='Состав')
    category = models.ForeignKey(Category,on_delete=models.CASCADE,default=Category.DEFAULT_PK)

    def price(self):
        return PriceCheanges.objects.select_related('item').filter(item=self)


    def get_absolute_url(self):
        return f'/category/{self.category}'+'/'+f'{self.slug}'

    class Meta:
        verbose_name_plural ='Продукты'
        verbose_name = 'Продукт'
        ordering = ['id']






class PriceCheanges(models.Model):


    date = models.DateTimeField()
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    old_price = models.DecimalField(default=100.00,max_digits=9, decimal_places=2, verbose_name='Цена')
    price = models.DecimalField(default=100.00,max_digits=9, decimal_places=2, verbose_name='Цена по скидке')

    def __str__(self):
        return str(self.price)

receipt/models.py
from django.db import models

# Create your models here.

main/views.py
from main.models import Item, RootCategory, Category
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import F
def sales_view(request):
    products_list = Item.objects.filter(pricecheanges__old_price__gt=F('pricecheanges__price')).distinct().order_by("?")
    category = {"name": 'Скидки недели'}
    paginator = Paginator(products_list, 200)

    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return render(request, 'main-page.html',
                  {'products': products, "categories": RootCategory.objects.all(), 'category': category})


def main_view(request):
    products_list = Item.objects.filter(popular=True)
    category = {"name": 'Полярные товары'}
    paginator = Paginator(products_list, 25)
    page = request.GET.get('page')

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'main-page.html', {'products': products, "categories": RootCategory.objects.all(), 'category': category})


def page_view(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products_list = category.get_products.order_by('id')
    paginator = Paginator(products_list, 25)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return render(request, 'main-page.html', {'products': products, "categories": RootCategory.objects.all(), 'category': category})


def item_view(request, name, slug):
    products = Item.objects.get(slug=slug)
    return render(request, 'item-page.html', {'products': products, "categories": RootCategory.objects.all()})

receipt/views.py
from django.shortcuts import render
from main.models import Item
from django.db.models import Q
# Create your views here.

def receipt(request):
    a = Item.objects.filter(name__search='Молоко')
    return render(request, 'untitled.html', {'items': a} )

templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>PriceStat</title>
    <link rel="stylesheet" href="/static/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/static/assets/css/Sidebar-Menu-1.css">
    <link rel="stylesheet" href="/static/assets/css/Sidebar-Menu.css">
    <link rel="stylesheet" href="/static/assets/css/styles-1.css">
    <link rel="stylesheet" href="/static/assets/css/styles.css">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {packages: ['corechart', 'line']});

        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Date', 'Discount price', 'Price'],
                {% for obj in products.price %}
                    [new Date('{{ obj.date|date}}'),{{ obj.price }}, {{ obj.old_price }}],
                {% endfor %}
            ]);

            var dateTicks = [];

            for (var m = {{products.price.0.date|date:"n" }}; m <= {{products.price.last.date|date:"n" }}+1; m++)
                    dateTicks.push(new Date('2021-' + m + '-1'));

            var options = {
                    legend: { position: 'bottom' },
                    axisTitlesPosition:'in',
                    height: 400,
                    hAxis: {format: 'MMMM',  ticks: dateTicks  },
                };

            // Instantiate and draw our chart, passing in some options.
            var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
            chart.draw(data, options);

            // Paul Irish’s Debounced resize plug-in
            $(window).smartresize(function () {
            chart.draw(data, options);
            });
        }
    </script>
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-md d-xl-flex align-items-xl-end navigation-clean" style="background-color: #1C461C;">
        <div class="container">
            <div class="row d-flex justify-content-start align-items-center" style="margin-right: 0px;margin-left: 0px;height: 83%;min-height: 100%;margin-top: -6px;">
                <div class="col-12 col-sm-4 col-md-3 col-lg-5 col-xl-5 text-left d-flex justify-content-center align-items-center justify-content-sm-center justify-content-md-center justify-content-lg-center" style="height: 100%;padding: 0px;"><a class="navbar-brand d-flex justify-content-center align-items-center" href="/" style="color: rgb(255,255,255);height: 43px;">Price-Stat</a></div>
                <div class="col-12 col-sm-8 col-md-9 col-lg-7 col-xl-7" style="height: 100%;width: 100%;">
                    <form class="form-inline d-flex justify-content-center align-items-center mr-auto" target="_self" style="height: 100%;width: 100%;">
                        <div class="form-group">
                            <div class="form-row d-flex justify-content-center align-items-center" style="height: 100%;width: 93%;">
                                <div class="col-2 d-flex justify-content-center align-items-center" style="height: 100%;padding: 0px;"><i class="fa fa-search d-flex justify-content-center align-items-center" style="color: rgb(255,255,255);margin-right: 9px;"></i></div>
                                <div class="col-10" style="height: 100%;"><input class="form-control search-field" type="search" id="search-field" name="search" style="background-color: #2F502F;width: 100%;"></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </nav>



    <div id="wrapper">
        <div id="sidebar-wrapper" style="background-color: #032103;padding-bottom: 9px;">
            <div><a class="btn d-xl-flex justify-content-xl-start" aria-expanded="true"  href="/" role="button" style="width: 100%;font-family: Roboto, sans-serif;font-size: 14px;color: #ffffff;">Популярные товары</a></div>
            <div><a class="btn d-xl-flex justify-content-xl-start" aria-expanded="true"  href="/sales" role="button" style="width: 100%;font-family: Roboto, sans-serif;font-size: 14px;color: #ffffff;">Скидки</a></div>

            {% for category in categories %}
            <div><a class="btn d-xl-flex justify-content-xl-start" data-toggle="collapse" aria-expanded="true" aria-controls="collapse-{{ category.id }}" href="#collapse-{{ category.id }}" role="button" style="width: 100%;font-family: Roboto, sans-serif;font-size: 14px;color: #c9c9c9;">{{ category.name }}</a>
                <div class="collapse" id="collapse-{{ category.id }}">
                    <ul class="nav nav-tabs border-0" style="width: 100%;">
                        {% for childcategory in category.category_set.all %}
                            <li class="nav-item" style="width: 100%;margin-bottom: 0px;"><a class="nav-link" href="/category/{{ childcategory.slug }}"style="width: 100%;font-size: 12px;color: #9b9999;background-color: #053205;font-family: Roboto, sans-serif;">{{ childcategory.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>

            </div>
            {% endfor %}
        </div>

        <div class="page-content-wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <script src="/static/assets/js/jquery.min.js"></script>
    <script src="/static/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/assets/js/chart.min.js"></script>
    <script src="/static/assets/js/bs-init.js"></script>
    <script src="/static/assets/js/Sidebar-Menu.js"></script>
</body>

</html>

templates/item-page.html
{% extends 'index.html' %}
{% block content %}
<div class="container-fluid"><a class="btn btn-link" role="button" id="menu-toggle" href="#menu-toggle"><i class="fa fa-bars" style="color: #4e7e4e;"></i></a>
    <div class="row">
        <div class="col-12 col-sm-auto col-md-auto col-lg-auto col-xl-auto" style="margin-top: 30px;width: 100%;">
            <div class="row" style="margin-bottom: 0px;margin-top: 25px;max-width: 95%;">
                <div  class="col-md-12 col-lg-6 col-xl-7" style="margin-bottom: 0px;padding-left: 0px;margin-left: 0px;padding-right: 0px;">
                    <h1 style="font-family: 'Roboto Slab', serif;font-size: 28px;font-weight: 700;color: rgb(51,51,51);">{{ products.name }}</h1>
                    {% if products.description|length > 1 %}
                    <h1 style="font-family: Roboto, sans-serif;font-size: 14px;color: rgb(155,153,153);">Описание</h1>
                    <p style="padding-left: 10px;font-family: Roboto, sans-serif;font-size: 14px;color: rgb(51,51,51);">{{ products.description|linebreaksbr }}</p>
                    {% endif %}
                    {% if products.composition|length > 1 %}
                    <h1 style="font-family: Roboto, sans-serif;font-size: 14px;color: rgb(155,153,153);">Состав</h1>
                    <p style="padding-left: 10px;font-family: Roboto, sans-serif;font-size: 14px;color: rgb(51,51,51);">{{ products.composition|linebreaksbr }}</p>
                    {% endif %}
                    {% if products.weight|length > 1 %}
                    <h1 style="font-family: Roboto, sans-serif;font-size: 14px;color: rgb(155,153,153);">Вес. {{ products.weight|linebreaksbr }}</h1>
                    {% endif %}
                    <h1 class="text-center" style="font-family: Roboto, sans-serif;font-size: 16px;color: rgb(0,0,0);">Статистика цен</h1>
                    <div id="chart_div" style="width: 100%;"></div>
            </div>
                <div class="col-md-12 col-lg-6 col-xl-5" style="padding-left: 0px;padding-right: 0px;">
                    <div class="row text-center d-sm-flex d-lg-flex d-xl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-lg-center justify-content-xl-center slider-for" id="uyt" style="background-color: rgba(0,0,0,0);padding-left: 0px;margin-left: 0px;">
                        <div class="col-12 col-sm-12 col-md-10 col-xl-8 text-center m-auto" style="margin-left: 0px;">
                            <img class="img-thumbnail center-block" id="first" src="{{products.large }}" style="width:100%;">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/main-page.html
{% extends 'index.html' %}
{% block content %}
    <style>
    @media (min-width: 993px) {
  .col-xl-3 {
    -webkit-box-flex: 0;
    -ms-flex: 0 0 20% !important;
    flex: 0 0 20% !important;
    max-width: 20%;
  }
}
    </style>
<div class="container-fluid"><a class="btn btn-link" role="button" id="menu-toggle" href="#menu-toggle"><i class="fa fa-bars" style="color: #4e7e4e;"></i></a>
                <div class="row">
                    <div class="col-12 col-sm-auto col-md-auto col-lg-auto col-xl-auto" style="margin-top: 30px;width: 100%;padding-left: 0px;padding-right: 0px;">
                        <h1 class="text-center" style="margin-bottom: 4px;margin-top: -20px;font-size: 34px;">{{ category.name }}</h1>
                        <div class="row">
                            {% for obj in products%}
                                <div class="col-sm-6 col-md-4 col-lg-4 col-xl-3" style="padding: auto;padding-top: 20px;padding-right: 20px;padding-bottom: 20xp;padding-left: 20px;">
                                <div class="block__inner">
                                    <a href="{{ obj.get_absolute_url }}"><img class="image" src="{{ obj.large }}" style="padding: 3px;max-width: 100%;object-fit: scale-down;"></a>
                                </div>
                                {% if obj.pricecheanges_set.last.price  < obj.pricecheanges_set.last.old_price %}
                                <s style="color: #57cc0f;"><h2 style="margin-bottom: 0px;opacity: 0.91;font-size: 14px;font-family: Roboto, sans-serif;font-weight: 600;color: #57cc0f;">{{ obj.pricecheanges_set.last.old_price }}</h2></s>
                                {% endif %}
                                <h2 style="margin-bottom: 0px;opacity: 0.91;font-size: 24px;font-family: Roboto, sans-serif;font-weight: 600;">{{ obj.pricecheanges_set.last.price }}</h2>
                                <h2 style="margin-bottom: 0px;opacity: 0.91;font-size: 14px;font-weight: 400;font-family: Roboto, sans-serif;color: rgb(51,51,51);">{{ obj.name|truncatechars:52 }}</h2>
                                <h2 style="margin-bottom: 0px;opacity: 0.91;font-size: 14px;font-weight: 400;font-family: Roboto, sans-serif;color: rgb(139,152,164);">{{ obj.display_weight }}</h2>
                                </div>
                            {% endfor %}
                        </div>
                        <footer class="rounded-0" style="margin-top: 17px;">
                            <nav class="text-center d-xl-flex justify-content-xl-center">
                                <ul class="pagination">
                                    {% if products.has_previous %}
                                        <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                                    {% endif %}
                                    {% for page in products.paginator.page_range %}
                                        <li class="page-item"><a class="page-link" href="?page={{page}}">{{ page }}</a></li>
                                    {% endfor %}
                                    {% if products.has_next %}
                                        <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </footer>
                    </div>
                </div>
            </div>
{% endblock %}